# Generated by Django 3.2.1 on 2021-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='order_id')),
                ('address', models.CharField(default='Нет адреса', max_length=256, verbose_name='address')),
                ('cargo', models.CharField(default='Нет груза', max_length=256, verbose_name='cargo')),
                ('weight', models.IntegerField(default=0, verbose_name='weight')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='order_id')),
                ('latitude', models.FloatField(default=0.0, verbose_name='latitude')),
                ('longitude', models.FloatField(default=0.0, verbose_name='longitude')),
                ('orderby_coordinates', models.IntegerField(default=0, verbose_name='orderby_coordinates')),
                ('orderby_distance', models.IntegerField(default=0, verbose_name='orderby_distance')),
                ('orderby_price', models.IntegerField(default=0, verbose_name='orderby_price')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
    ]
