# Generated by Django 3.2.1 on 2021-05-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='arrival_date')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('cargo', models.CharField(max_length=256, verbose_name='cargo')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('user', models.CharField(max_length=64, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
